/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "udivdeelpkkxlhjzxbcf";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaXZkZWVscGtreGxoanp4YmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQ4MDIsImV4cCI6MjA2OTEzMDgwMn0.JzTBWTTnwnRHTrLiJ48wxhbW8ancQSrlL0aYf-GAiv0";

if (!projectId || !publicAnonKey) {
  throw new Error('Missing Supabase credentials');
}
